# f9ctl fish 补全（手工维护）。
complete -c f9ctl -n '__fish_use_subcommand' -a 'devices' -d '列出设备与可用传输'
complete -c f9ctl -n '__fish_use_subcommand' -a 'status' -d '读取实时状态与转速'
complete -c f9ctl -n '__fish_use_subcommand' -a 'info' -d '读取设备信息'
complete -c f9ctl -n '__fish_use_subcommand' -a 'mode' -d '挡位操作'
complete -c f9ctl -n '__fish_use_subcommand' -a 'monitor' -d '持续监控'
complete -c f9ctl -n '__fish_use_subcommand' -a 'daemon' -d '守护进程管理'
complete -c f9ctl -n '__fish_use_subcommand' -a 'config' -d '配置文件操作'
complete -c f9ctl -n '__fish_use_subcommand' -a 'debug' -d 'raw 调试'
complete -c f9ctl -s v -l verbose -d '详细日志'
complete -c f9ctl -l no-daemon -d '绕过 f9d IPC'
complete -c f9ctl -l transport -x -a 'auto usb ble' -d '传输选择'
complete -c f9ctl -l output -x -a 'human json' -d '输出格式'
complete -c f9ctl -l device -x -d '设备选择器'
complete -c f9ctl -l timeout -x -d '超时'
complete -c f9ctl -n '__fish_seen_subcommand_from mode; and not __fish_seen_subcommand_from get set' -a 'get set'
complete -c f9ctl -n '__fish_seen_subcommand_from mode; and __fish_seen_subcommand_from set' -a 'quiet balanced beast turbo'
complete -c f9ctl -n '__fish_seen_subcommand_from devices' -a 'list'
complete -c f9ctl -n '__fish_seen_subcommand_from daemon' -a 'install uninstall start stop restart status logs run'
complete -c f9ctl -n '__fish_seen_subcommand_from config' -a 'path show validate'
complete -c f9ctl -n '__fish_seen_subcommand_from debug' -a 'raw'
